### PR TITLE
Move whitelistedDomains to simple storage (issue #24)

### PR DESCRIPTION
**Pull request by monicachew**

### CODE REVIEW

**Comment by mozkeeler** [comment]
LGTM. You know "SS" often refers to the Schutzstaffel, right?

**Comment by monicachew** [comment]
I think you just godwined our project ;)

**Comment by gregglind** [comment]
(Warning from addon-sdk-land)

`simple-storage` keeps it all "live" as a js object, that gets synced to backend store.   It's not recommended for over a few MB of storage.  

If you want to do go deeper, IndexedDb might be a way to go.

**Comment by monicachew** [comment]
Good point. I think we should wait til scaling issues are closer before actually scaling. We are currently at 11K and 16K for the search terms and url list, using the dumbest possible data structure, with no compression, so I think it will be a while.

**Pull request merged**
